Alamofire 5+ migration
RedMadRobot/http-transport pull request #3
Opened 2020-10-15 10:25 UTC by BoykoMihail

Try migrate to Alamofire 5+

2020-10-15 12:46 UTC, modestman requested changes

2020-10-15 12:46 UTC, modestman commented on HTTPTransport.podspec
> +  s.version      = "4.2.0"
В HTTPTransport.podspec необходимо указать минимальную версию Alamofire и поднять версию iOS
```
s.platform     = :ios, "10.0"
s.dependency "Alamofire", "~> 5.2"
```

Поменялось публичное API библиотеки HTTPTransport, я думаю можно поднять версию до 5.0
```
s.version      = "5.0.0"
```

2020-10-15 12:46 UTC, modestman commented on HTTPTransport.podspec
> +  s.version      = "4.2.0"
Также, в Example/Podfile поднять версию 
```
platform :ios, '10.0'
```

2020-10-15 12:48 UTC, modestman commented
При запуске Example проекта возникают ошибки. `Error` не того типа, получено `AFError`, а ожидалось `NSError`

![image](https://user-images.githubusercontent.com/1762267/96128104-9be62c80-0efd-11eb-8fe3-7ef19bada1be.png)

2020-10-15 12:50 UTC, modestman commented
В файлах из модуля Digest много warning-ов. Я думаю всю папку Digest можно удалить, а вызовы `sha1` и `sha256` заменить на системные из CommonCrypto

2020-10-15 14:06 UTC, vani2 requested changes

2020-10-15 14:06 UTC, vani2 commented on Source/HTTPTransport/HTTPTransport/Classes/Helper/HTTPTransportRetrier.swift
> +                     guard let `self` = self
Swift 5 можно опустить одинарные кавычки
`guard let self = self`

2020-10-15 14:06 UTC, vani2 commented on Source/HTTPTransport/HTTPTransport/Classes/Helper/HTTPTransportRetrier.swift
> +                     self.requestsToRetry.removeAll()
отступ поехал

2020-10-15 18:16 UTC, modestman commented on Source/Example/Podfile
> +	pod 'HTTPTransport', :git => 'git@github.com:BoykoMihail/http-transport.git', :branch => 'master'
Здесь можно заменить на 
```
pod 'HTTPTransport', :path => '../..'
```

2020-10-16 10:09 UTC, modestman approved these changes

2020-10-16 10:21 UTC, modestman commented
@taflanidi Привет, можешь посмотреть PR и если все ок, то опубликовать новую версию в Cocoapods?

2020-10-19 08:56 UTC, BoykoMihail commented
@vani2 @taflanidi Привет! Можете посмотреть PR пожалуйста?

2020-10-19 09:37 UTC, vani2 approved these changes

2020-10-19 11:04 UTC, taflanidi commented
Привет, гляну.

2020-11-24 08:51 UTC, petropavel13 commented
@taflanidi удалось посмотреть?

2020-11-24 08:57 UTC, taflanidi commented
@petropavel13 чуваки, мои извинения.
На голову свалилась куча задач.

Вот прям сейчас проверю и опубликую (-:

2020-11-24 08:57 UTC, merged

2020-11-24 09:16 UTC, taflanidi commented
@BoykoMihail @modestman @petropavel13 @vani2 
Готово.